### ISSUE TITLE
Retrieve entries after association

### ISSUE THREAD

**Issue by mvrk69** [daynt/KeePassHTTP-Python#1]
Hi,

If i run like this, it makes the association and retrieves the logins ok:

kp = KeePassHTTP();
kp.key = "**********************";
kp.associate();
# kp.is_running();
# kp.is_associate();

kp.get_logins("https://xxxxxxxxxxxxxxxxxxxxxxxx.xxx");

But i shouldn't run associate every time right?

So, now after the 1st association, i run like this:

kp = KeePassHTTP();
kp.key = "**********************";
kp.is_running();
kp.is_associate();
kp.get_logins("https://xxxxxxxxxxxxxxxxxxxxxxxx.xxx");

and i get this error:

Traceback (most recent call last):
  File "./keepasshttp.py", line 130, in <module>
    kp.get_logins("https://xxxxxxxxxxxxxxxxxxxxxxxx.xxx")
  File "./keepasshttp.py", line 74, in get_logins
    self._response_verfier(response)
  File "./keepasshttp.py", line 46, in _response_verfier
    generate_nonce = self._decrypt_data(base64.b64decode(response['Verifier']),
KeyError: 'Verifier'

Any ideas? Am i doing anything wrong?

**Comment by daynt** [comment]
mhhh. ya, you dont save the key identifier.

# register key

```

kp = KeePassHTTP()
# check if keepass is open
while not kp.is_running():
    time.sleep(1)

#register key
kp.associate()

# key name
id = kp.id
# key
key = kp.key

```

# check key and get login

```
kp.id = "example name"
kp.key = "randomaeskey"


#check key
if not kp.is_associate():
    print 'key could not found in keepass'

login = kp.get_logins('https://example.com')
```

I hope this will help you.

**Comment by mvrk69** [comment]
yes, i saved the ID and the KEY to a file after the association and now i read it from that file and works. Thanks for the help.
